<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Funcionario extends Model
{
    protected $fillable = ['FUNCIONARIO_RUT','FUNCIONARIO_NOMBRES','FUNCIONARIO_AP_PATERNO','FUNCIONARIO_AP_MATERNO','FUNCIONARIO_FEC_NAC','FUNCIONARIO_DOMICILIO','CIUDAD_ID','FUNCIONARIO_EMAIL','FUNCIONARIO_FONO_CEL','FUNCIONARIO_FONO_FIJO','FUNCIONARIO_IMG','FUNCIONARIO_FLAG'];
}
